### PR TITLE
Bind rabbitmq statefulset to linux nodes to avoid Windows scheduling on kubernetes cluster includes linux nodes and windows nodes

### PR DESCRIPTION
**Pull request by wawa0210**
## Proposed Changes

Bind rabbitmq statefulset to linux nodes to avoid Windows scheduling on kubernetes cluster includes linux nodes and windows nodes( since kubernetes 1.14 windows node already ga )

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [x] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wawa0210 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-peer-discovery-k8s&pullRequestId=53)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-peer-discovery-k8s&pullRequestId=53) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@wawa0210 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-peer-discovery-k8s&pullRequestId=53)!

**Comment by michaelklishin** [comment]
Thank you. We are supposed to [use `kubernetes.io/os` now](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#kubernetes-io-os). I will update before merging.

**Comment by wawa0210** [comment]
> Thank you. We are supposed to [use `kubernetes.io/os` now](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#kubernetes-io-os). I will update before merging.

Both of two labels are exists

**Comment by michaelklishin** [comment]
Yes but Kubernetes docs explicitly state that one of them is deprecated :) Anyhow, thanks for contributing 👍🥇

**Comment by wawa0210** [comment]
> Yes but Kubernetes docs explicitly state that one of them is deprecated :) Anyhow, thanks for contributing 👍🥇

Thx, then i request again and change the newer label

**Comment by wawa0210** [comment]
> Yes but Kubernetes docs explicitly state that one of them is deprecated :) Anyhow, thanks for contributing 👍🥇
You already changed the newer label 👍👍👍

**Pull request merged**
