### PR TITLE
Change from POD IP to POD Name

### PR DESCRIPTION
**Pull request by Gsantomaggio**
## Proposed Changes

Small improvement for the example
Change from POD IP to POD NAME, it is important when persistent the data. 
In case of restart the IP _may_ change  but the hostname is the same,
so the cluster could not work correctly.

## What types of changes does your code introduce to this project?

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [X] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist
- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

See also the [chart ](https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/templates/statefulset.yaml#L140)

### CODE REVIEW

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Thank you!

**Comment by michaelklishin** [comment]
@gerhard FYI.

**Comment by michaelklishin** [comment]
Backported to `v3.7.x`.

**Comment by gerhard** [comment]
cc @mkuratczyk

**Pull request merged**
